In [3]:
import numpy as np

In [4]:
#Initial inputs

inputs = np.array([1,2,3,4])

# Initial weights and biases

weights = np.array([
    [0.1,0.2,0.3,0.4],
    [0.5,0.6,0.7,0.8],
    [0.9,1.0,1.1,1.2]
])

In [5]:
biases = np.array([0.1,0.2,0.3])

In [7]:
# Learning rate

learning_rate = 0.001


# ReLU activation function and its derivative

def relu(x):
    return np.maximum(0,x)

def relu_derivative(x):
    return np.where(x > 0,1,0)

# Training loop
for iteration in range(200):
    # Forward pass
    z = np.dot (weights,inputs) +biases
    a = relu(z)
    y = np.sum(a)

    #Calculate loss
    loss = y ** 2

    # Backward pass
    # Gradient of loss with respect to output y
    dL_dy = 2 * y

    # Gradient of loss with respect to output y
    dy_da = np.ones_like(a)

    # Gradient of loss with respect to a

    dL_da = dL_dy* dy_da 

    # Gradient of a with respect to z (ReLU derivative)

    da_dz = relu_derivative(z)

    # Gradient of loss with respect to z

    dL_dz = dL_da * da_dz

    # Gradient of z with respect to weights and biases

    dL_dw = np.outer(dL_dz, inputs)
    dL_db = dL_dz 


    # Update weights and biases

    weights -= learning_rate*dL_dw
    biases -= learning_rate*dL_db

    # Print the loss every 20 interation 

    if iteration % 20 == 0:
        print(f"Iteration {iteration}, Loss: {loss}")


# Final weights and biases
print("Final weights:\n", weights)
print("Final biases: \n", biases)





Iteration 0, Loss: 5.244645462659219e-10
Iteration 20, Loss: 4.0534952695210353e-11
Iteration 40, Loss: 3.132875999354687e-12
Iteration 60, Loss: 2.42134537657066e-13
Iteration 80, Loss: 1.8714157315955333e-14
Iteration 100, Loss: 1.446384677446104e-15
Iteration 120, Loss: 1.117885573813104e-16
Iteration 140, Loss: 8.639942892432007e-18
Iteration 160, Loss: 6.677661257483395e-19
Iteration 180, Loss: 5.161046100041788e-20
Final weights:
 [[-0.00698895 -0.01397789 -0.02096684 -0.02795579]
 [ 0.25975286  0.11950572 -0.02074143 -0.16098857]
 [ 0.53548387  0.27096774  0.00645161 -0.25806452]]
Final biases: 
 [-0.00698895 -0.04024714 -0.06451613]


### Using Matrices in Backpropagation