## Building Blocks of Backpropgation


In [1]:
import numpy as np

### GRADINETS OF THE LOSS WITH RESPECT TO WEIGHTS

In [3]:
# Passed-in gradient from the next layer
# for the purpose of this example we're going to use
# an array of an incremental gradient values

dvalues = np.array([[1.,1.,1.],[2.,2.,2.],[3.,3.,3.]])

# We have 3 sets of inputs - samples
inputs = np.array([[1,2,3,2.5],[2.,5.,-1.,2],[3.,3.,3.,-0.8]])
# sum weights of given input 
# and multiply by the passed-in gradient for this neuron
dweights = np.dot(inputs.T, dvalues)
print(dweights)

[[14.  14.  14. ]
 [21.  21.  21. ]
 [10.  10.  10. ]
 [ 4.1  4.1  4.1]]


### GRADINETS OF THE LOSS WITH RESPECT TO BIASES

In [4]:
dvalues = np.array([[1.,1.,1.],[2.,2.,2.],[3.,3.,3.]])
# One bias for each neuron
# biases are the row vector with a shape (1,neurons)
biases = np.array([[2,3,0.5]])
# dbiases - sum values , do this over samples (first axis), keepdims
# since this by default will produce a plain list -

dbiases = np.sum(dvalues,axis=0,keepdims=True)
print(dbiases)

[[6. 6. 6.]]


### GRADINETS OF THE LOSS WITH RESPECT TO INPUTS

In [6]:
dvalues = np.array([[1.,1.,1.],[2.,2.,2.],[3.,3.,3.]])

# we have 3 sets of weights - one set for each neuron
# we have 4 inputs , thus 4 weights
# recall that we keep weights transposed
weights = np.array([[0.2,0.8,-0.5,1],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]).T

# sum weights of given input
# and multiply by the passed in gradient for this neuron
dinputs = np.dot(dvalues,weights.T)
print(dinputs)

[[ 0.44 -0.38 -0.07  1.37]
 [ 0.88 -0.76 -0.14  2.74]
 [ 1.32 -1.14 -0.21  4.11]]


### ADDING THE "BACKWARD" METHOD IN THE LAYER-DENSE CLASS