#### Softmax Classifier - Combined Softmax activation and cross-entropy loss for faster backward step

In [1]:
%run 5_Cross_Entropy_Loss.ipynb

[0.7 0.5 0.9]
[[0.35667494 2.30258509 1.60943791]
 [2.30258509 0.69314718 0.91629073]
 [3.91202301 0.10536052 2.52572864]]
0.38506088005216804
[0.35667494 0.69314718 0.10536052]
0.38506088005216804
0.38506088005216804


In [3]:
import numpy as np

In [7]:
# Softmax activation
class Activation_Softmax:
 # Forward pass
 def forward(self, inputs):
 # Get unnormalized probabilities
  exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
 # Normalize them for each sample
  probabilities = exp_values / np.sum(exp_values, axis=1,keepdims=True)
  self.output = probabilities

In [8]:
# Softmax classifier - combined Softmax activation
# and cross- entropy loss for faster backward step

class Activation_Softmax_Loss_CategoricalCrossentropy:
    # Create activation and loss function objects

    def __init__(self):
        self.activation = Activation_Softmax()
        self.loss = Loss_CategoricalCrossentropy()

    # Forward pass

    def forward(self,inputs,y_true):
        # Output layer's actiavtion function

        self.activation.forward(inputs)
        # Set the output 

        self.output = self.activation.output 
        # calculate and return loss value 
        return self.loss.calculate(self.output, y_true)


        # Backward pass

    def backward(self,dvalues,y_true):
        # Number of samples
        samples = len(dvalues)

        # If labels are one-hot encoded,
        # turn them into discrete values
        if len(y_true.shape) == 2:
            y_true = np.argmax(y_true,axis=1)

        # Copy so we can safely modify 
        self.dinputs = dvalues.copy()

        # Calculate gradient

        self.dinputs[range(samples),y_true] -= 1

        # Normalize gradient

        self.dinputs = self.dinputs / samples 
        






In [9]:
 softmax_outputs

array([[0.7 , 0.1 , 0.2 ],
       [0.1 , 0.5 , 0.4 ],
       [0.02, 0.9 , 0.08]])

In [10]:
class_target = np.array([0,1,1])
softmax_loss = Activation_Softmax_Loss_CategoricalCrossentropy()
softmax_loss.backward(softmax_outputs, class_target)
dvalues1 = softmax_loss.dinputs 
print('Gradients: combined loss and activation :')
print(dvalues1)

Gradients: combined loss and activation :
[[-0.1         0.03333333  0.06666667]
 [ 0.03333333 -0.16666667  0.13333333]
 [ 0.00666667 -0.03333333  0.02666667]]
