# Dense Layer Class


In [10]:

import numpy as np
import nnfs 
from nnfs.datasets import spiral_data  

In [11]:
class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
    # Initialize weights and biases
        self.weights = 0.01* np.random.randn(n_inputs,n_neurons)
        self.biases = np.zeros((1,n_neurons))

    # Forward pass
    def forward(self,inputs):
    # Calculate output values from inputs, weights and biases
        self.output = np.dot(inputs,self.weights) + self.biases

        



        

In [13]:
# Create datset

X,y = spiral_data(samples=100, classes=3)

print(X)
print(y)


[[ 0.00000000e+00  0.00000000e+00]
 [-4.99705298e-03  8.77837494e-03]
 [ 4.51674482e-03  1.96906231e-02]
 [ 2.12454368e-02  2.16079861e-02]
 [-1.07896314e-02  3.89367479e-02]
 [ 3.56224221e-02  3.58022789e-02]
 [ 4.01037317e-02  4.54399085e-02]
 [ 6.65573271e-02  2.38665469e-02]
 [ 7.93722747e-02  1.51653533e-02]
 [ 3.21208672e-02  8.50453567e-02]
 [ 4.86090351e-02  8.85449164e-02]
 [ 9.38760453e-02  5.94387680e-02]
 [ 1.20822400e-01 -9.71215415e-03]
 [ 1.24651783e-01 -4.12925111e-02]
 [ 1.28271426e-01  5.95348684e-02]
 [ 1.07040578e-01  1.07234117e-01]
 [ 1.44591186e-01 -7.22023025e-02]
 [ 1.61000976e-01  5.97115797e-02]
 [ 1.06938905e-01 -1.47043946e-01]
 [ 1.65092378e-01 -9.78646147e-02]
 [ 1.91624381e-01 -6.39707633e-02]
 [ 2.02888451e-01 -6.19006069e-02]
 [ 1.92494296e-01 -1.11034508e-01]
 [ 2.31011786e-01 -2.46503314e-02]
 [ 2.14641149e-01 -1.12688467e-01]
 [ 2.25514962e-01 -1.13631004e-01]
 [ 2.62609334e-01  2.98183323e-03]
 [-9.82713335e-02 -2.54406978e-01]
 [ 1.64111205e-01 -2

In [14]:

# Create Dense layer with 2 input features and 3 output values

dense1 = Layer_Dense(2,3)

In [15]:
# Perform a forward pass of out training data through this layer

dense1.forward(X)
# Let's see output of the first few samples:
print(dense1.output[:5])

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-4.09272083e-05  3.79359459e-05  9.40024564e-05]
 [-2.44317166e-04  1.45459346e-05  5.02061539e-05]
 [-4.26084875e-04 -5.71123865e-05 -1.11309047e-04]
 [-2.91853669e-04  1.17236047e-04  3.00746480e-04]]
