#### This is the previous code (Scroll down to LOSS FUNCTION section)

In [2]:
import nnfs 
from nnfs.datasets import spiral_data  

In [15]:
%run 3_Activaton_function_Scratch.ipynb # used to import Layer_dense class
%run 1_Dense_Layer_Class.ipynb  # used to import Activation Functions classes
%run 5_Cross_Entropy_Loss.ipynb # used to import loss function

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]
[[0.06414769 0.17437149 0.47399085 0.28748998]
 [0.04517666 0.90739747 0.00224921 0.04517666]
 [0.00522984 0.34875873 0.63547983 0.0105316 ]]
[[ 0.00000000e+00  0.00000000e+00]
 [ 1.64456131e-03  9.96623415e-03]
 [ 3.80512100e-03  1.98404303e-02]
 [ 1.44562549e-02  2.66325053e-02]
 [-1.54010897e-02  3.73536198e-02]
 [ 1.25188288e-02  4.89289183e-02]
 [-4.03774508e-02  4.51968588e-02]
 [ 4.26584692e-02  5.63892264e-02]
 [ 6.76000052e-02  4.42739791e-02]
 [ 7.83130191e-02  4.61685375e-02]
 [ 6.50030031e-02  7.73152643e-02]
 [ 9.39964719e-02  5.92481415e-02]
 [ 9.83814515e-02  7.08058495e-02]
 [ 1.07897356e-01 -7.48418266e-02]
 [ 1.41138683e-01 -8.82221736e-03]
 [ 1.45381305e-01  4.26745497e-02]
 [ 7.58661102e-02  1.42702898e-01]
 [ 1.70855233e-01  1.71836135e-02]
 [ 1.66165267e-01  7.38034905e-02]
 [ 1.78322607e-01 -7.09508566e-02]
 [ 2.00981316e-01 -2.04614941e-02]
 [ 1.71413494e-01 -1.24951281e-01]
 [ 2.19101057e-01  3.71139189e-02]
 [ 2.02892986e-01 -

In [16]:
softmax = Acitvation_Softmax()

In [17]:
# Create dataset

X,y = spiral_data(samples=100,classes=3)

In [18]:
#Create Dense layer with 2 input features and 3 output values

dense1 = Layer_Dense(2,3)

In [19]:
# Create ReLU actiavation 
activation1 = Activation_ReLU()

In [20]:
#Create second Dense layer with 3 input features (as we take output of previous layer here )
# and 3 output values

dense2 = Layer_Dense(3,3)

In [21]:
# Create Softmax actiavtion (to be used with Dense layer):
activation2 = Acitvation_Softmax()

In [22]:
# Make a forward pass of our training data througth this layer

dense1.forward(X)

In [23]:
# Make a forward passs through activaton function
# it takes the output of first dense layer here
activation1.forward(dense1.output)


In [24]:
# Make a forward pass throught second Dense layer
# it takes outputs of actiavtion function of first layer as inputs
dense2.forward(activation1.output)

In [25]:
# Make a forward pass throught activation function
# it  takes the output of second dense layer here
activation2.forward(dense2.output)

In [26]:
# let's see output of the first few samples:
print(activation2.output[:5])



[[0.33333333 0.33333333 0.33333333]
 [0.33333346 0.33333319 0.33333335]
 [0.33333367 0.33333298 0.33333334]
 [0.33333378 0.33333287 0.33333335]
 [0.33333402 0.33333263 0.33333335]]


# Loss Function from Here

In [27]:
loss = loss_function.calculate(activation2.output,y)
# Print loss value
print('loss :', loss)

loss : 1.0986127938764212


In [28]:
#Calculate accuracy from output of activaton2 and targets
# calculate values along first axis
predictions = np.argmax(activation2.output,axis=1)
if len(y.shape) == 2:
    y = np.argmax(y,axi=1)
accuracy = np.mean(predictions == y)
# Print accuracy

print('acc:', accuracy)

acc: 0.37


### INTRODUCING ACCURACY

In [30]:
import numpy as np

# Probabilities of 3 samples 
softmax_outputs = np.array([[0.7,0.2,0.1],[0.1,0.5,0.4],[0.02,0.9,0.08]])

# Target (ground-truth) labels for 3 samples 
class_targets = np.array([0,1,1])
# Calculate valeus along second axis (axis of index 1)
predictions = np.argmax(softmax_outputs,axis=1)

#if target are one-hot encoded - convert them 

if len(class_targets.shape) == 2:
    class_targets = np.argmax(class_targets,axis=1)
# True evaluates to 1; False to 0

accuarcy = np.mean(predictions == class_targets)
print('acc:', accuarcy)

acc: 1.0
